Add alternative address to the example code
adafruit/Adafruit_BMP280_Library pull request #50
Opened 2021-04-03 10:20 UTC by aljosamrak

Changes:
- add commented out code to use the predefined alternative address (0x76)
- add additional info to the error message to try a different address

Added these changes to help resolve the simple issue of the wrong address quicker.

2021-04-03 15:37 UTC, ladyada commented
hi please keep the 
while(1) delay(10);
because it will keep ESP chips from WDT

2021-04-03 15:42 UTC, ladyada requested changes
hi please keep the
while(1) delay(10);
because it will keep ESP chips from WDT

2021-04-03 17:36 UTC, aljosamrak commented
Hi,
Thank you for pointing it out. I've added it to the other example that didn't have the delay.

2021-04-04 01:20 UTC, ladyada approved these changes

2021-04-04 01:20 UTC, merged